---
title: "Data Cleaning"
output: pdf_document
---

```{r message=F, warning=F}
library(sf)
library(tidyverse)
```

```{r load_data, message=F, warning=F}
# Load data
crime_raw = st_read("Neighbourhood_Crime_Rates_2020.shp")
hood_profiles_raw = read_csv("neighbourhood-profiles-2016-csv.csv")
```

```{r}
# Select and clean crime counts for 2016
crime = crime_raw %>% select(OBJECTID, Neighbourh, Hood_ID, 
                         Assault__2,
                         AutoThef_2,
                         BreakAnd_2,
                         Robbery__2,
                         TheftOve_2,
                         Homicide_3,
                         Shooting_2
                         ) %>%
  rename(neighbourhood=Neighbourh, assault=Assault__2, auto_theft=AutoThef_2, 
         break_and_enter=BreakAnd_2, robbery=Robbery__2,
         theft_over=TheftOve_2, homicide=Homicide_3, shooting=Shooting_2
         ) %>%
  mutate(violent_crime = assault+homicide+shooting,
         theft = robbery+theft_over+auto_theft)
```

```{r}
# Filter to relevant data
hood_profiles = hood_profiles_raw %>% rename(id = `_id`) %>%
  filter(Characteristic %in% c("Aboriginal identity",
         "Children (0-14 years)", "Youth (15-24 years)", "Seniors (65+ years)",
         "Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)",
         "Unemployment rate",
         "Black", "Not a visible minority", "Population density per square kilometre",
         "Immigrants", "Population, 2016") 
         | id %in% c(1708, 1709, 1710)
         | Topic == "Visible minority population"
         | str_detect(Characteristic, "^Female:")
         ) %>%
  filter(Characteristic != "Total - Visible minority for the population in private households - 25% sample data",
         Characteristic != "Visible minority; n.i.e.",
         Characteristic != "Multiple visible minorities") %>%
  select(-id, -Category, -Topic, -`Data Source`, -`City of Toronto`)
hood_profiles
```

```{r message=F, warning=F}
# Transpose dataframe
characteristic = hood_profiles$Characteristic
hood_profiles = as.data.frame(t(hood_profiles[,-1]))
colnames(hood_profiles) = characteristic
hood_profiles = rownames_to_column(hood_profiles, "neighbourhood")

# Convert columns from string to numeric
hood_profiles[2:dim(hood_profiles)[2]] = lapply(hood_profiles[2:dim(hood_profiles)[2]], 
                                                 function(x) as.numeric(gsub(",", "", x)))
```

```{r}
# Rename columns
hood_profiles = hood_profiles %>% rename(pop="Population, 2016",
                         pop_density="Population density per square kilometre",
                         n_children="Children (0-14 years)",
                         n_youth="Youth (15-24 years)",
                         n_seniors="Seniors (65+ years)",
                         perc_low_income="Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)",
                         n_lat_american="Latin American",
                         n_aboriginal_identity="Aboriginal identity",
                         n_visible_minority="Total visible minority population",
                         south_asian="South Asian",
                         southeast_asian="Southeast Asian",
                         west_asian="West Asian",
                         not_visible_minority="Not a visible minority",
                         unemp_rate = "Unemployment rate"
                         )
```

```{r}
# Sum number of females by neighbourhood
hood_profiles$n_female = rowSums(select(hood_profiles, starts_with("Female:")))
hood_profiles = hood_profiles %>% select(-starts_with("Female:"))

# Sum number of people with post-secondary education by neighbourhood
hood_profiles$n_postsecondary = rowSums(select(hood_profiles, starts_with("College") | starts_with("University")))
hood_profiles = hood_profiles %>% select(-starts_with("College"), -starts_with("University"))
```

```{r}
# Create percentage data
hood_profiles = hood_profiles %>%
  mutate(n_asian=south_asian+Chinese+Filipino+southeast_asian+west_asian+Korean+Japanese,
         perc_children=n_children/pop*100,
         perc_youth=n_youth/pop*100,
         perc_seniors=n_seniors/pop*100,
         perc_lat_american=n_lat_american/pop*100,
         perc_immigrants=Immigrants/pop*100,
         perc_aboriginal=n_aboriginal_identity/pop*100,
         perc_visible_minority=n_visible_minority/pop*100,
         perc_south_asian=south_asian/pop*100,
         perc_chinese=Chinese/pop*100,
         perc_black=Black/pop*100,
         perc_Filipino=Filipino/pop*100,
         perc_Arab=Arab/pop*100,
         perc_southeast_asian=southeast_asian/pop*100,
         perc_west_asian=west_asian/pop*100,
         perc_Korean=Korean/pop*100,
         perc_Japanese=Japanese/pop*100,
         perc_not_visible_minority=not_visible_minority/pop*100,
         perc_female=n_female/pop*100,
         perc_postsecondary=n_postsecondary/pop*100,
         perc_asian=n_asian/pop*100
  )
```

```{r}
# Make neighbourhood names match betwen datasets
hood_profiles$neighbourhood = gsub("St. ", "St.", hood_profiles$neighbourhood)
hood_profiles[hood_profiles=="Weston-Pelham Park"] = "Weston-Pellam Park"
```

```{r}
# Merge data
data = merge(crime, hood_profiles, by = "neighbourhood")
```
